# On veut un front en react donc on utilise node comme image de base
FROM node:16.13.0

# On définit le répertoire de travail dans une variable d'environnement
ENV APP_HOME=/home/golden-rules

# On crée et se place dans le répertoire de travail
WORKDIR $APP_HOME

# On définit l'utilisateur qui va exécuter les commandes suivantes
USER root:root

# On copie les fichiers necessaires pour le frontend dans le répertoire de travail
COPY . $APP_HOME

# On installe les dépendances
RUN npm install

# On build le projet react
CMD [ "npm","run","build"]

