version: '3.3'

services:
  frontend:
    build:
      context: frontend
    volumes:
      - ./frontend/build:/home/golden-rules/build
    
  http:
    image: nginx
    volumes:
      - ./frontend/build:/usr/share/nginx/html
    ports:
      - 80:80
    depends_on:
      - frontend